# Generated by Django 4.1.5 on 2023-03-27 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_sales'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pur_qty', models.FloatField(default=0)),
                ('sale_qty', models.FloatField(default=0)),
                ('total_bal_qty', models.FloatField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.product')),
                ('purchas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.purchas')),
                ('sales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.sales')),
            ],
        ),
    ]
