# Generated by Django 4.1.5 on 2023-03-27 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_inventory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory',
            options={'verbose_name_plural': 'Inventory'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'Product'},
        ),
        migrations.AlterModelOptions(
            name='purchas',
            options={'verbose_name_plural': 'Purchase'},
        ),
        migrations.AlterModelOptions(
            name='sales',
            options={'verbose_name_plural': 'Sale'},
        ),
        migrations.AlterField(
            model_name='inventory',
            name='pur_qty',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='purchas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.purchas'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='sale_qty',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='sales',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.sales'),
        ),
    ]
