# Generated by Django 4.1.5 on 2023-03-28 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='customer',
        ),
        migrations.AddField(
            model_name='sales',
            name='cust_add',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='sales',
            name='customer_mob',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='sales',
            name='customer_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
