# Generated by Django 4.1.5 on 2023-03-30 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_alter_sales_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='price',
            field=models.FloatField(),
        ),
    ]
