# Generated by Django 4.1.5 on 2023-03-30 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_alter_sales_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='cust_add',
            field=models.CharField(default='Indore', max_length=150, null=True),
        ),
    ]
