# Generated by Django 4.1.5 on 2023-03-23 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_mobile_profile_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='phone',
            new_name='mobile',
        ),
    ]
