# Generated by Django 4.1.5 on 2023-03-23 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_phone_profile_mobile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='mobile',
            new_name='phone',
        ),
    ]
